#maths and Calculation
print("I could like to count my chicken")
print("Hens", 20 + 30 / 6)
print("Rossters", 100 - 20 * 3 / 2)
print("I could like to count egss:")
print(2 + 45 - 23 / 3 * 10 % 5)
print("It's true that 3 + 2 -4 < 5 -7?")
print(3+2<5-7)
print("Thats false")
print("it is greater", 5 > -2)
print("it is greater or less than", 5>= -2)
print("its equal or less", 5<= -2)
